version: "3.9"

services:
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      API_SECRET: ${API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_DSN: ${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}
    restart: on-failure

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  db_data:
