version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_SECRET=${API_SECRET}
      - DB_DSN=${DB_DSN}
    env_file:
      - .env
    restart: on-failure
