version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      API_SECRET: ${API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_DSN: ${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}
    depends_on:
      - db

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
